name: dhikri
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Media
  community_material_icon: ^5.9.55
  flutter_svg: ^2.0.10+1

  # Data Management
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Browser
  url_launcher: ^6.3.0

  # Other
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
          style: normal
